[package]
authors = ["Sergei Silnov <po@kumekay.com>"]
edition = "2018"
name = "pyaskalono"
version = "0.1.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
name = "askalono"

[dependencies]
askalono = { version = "0.5.0", default-features = false }
pyo3 = { version = "0.22.0", features = ["extension-module"] }
