name: Deploy to PyPI

on:
  push:
    branches:
      - main
      - feature/push_pypi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          architecture: x64
      - uses: dtolnay/rust-toolchain@stable
      - uses: PyO3/maturin-action@v1
        with:
          target: x86_64
          command: publish
          args: -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }} -r ${{ secrets.PYPI_REPO }} -i python3.11
